vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-LA29S3U\\VENKATESH
vti_modifiedby:SR|DESKTOP-LA29S3U\\VENKATESH
vti_timelastmodified:TR|17 Nov 2015 10:49:40 -0000
vti_timecreated:TR|06 Nov 2015 07:49:21 -0000
vti_title:SR|Recharge prepaid Mobile, DTH and Data Card, Mobile Recharge API
vti_extenderversion:SR|6.0.2.8161
vti_backlinkinfo:VX|index.php index.htm mobilerechargeapi.php qrfaq.php qrservices.php qrdisclaimer.php qrdistributor-ship.php qrretailer-ship.php qrregistration.php qrrefer.php qrpolicy.php qrpay2use.php qrnews.php
vti_nexttolasttimemodified:TW|17 Nov 2015 10:04:50 -0000
vti_cacheddtm:TX|17 Nov 2015 10:49:40 -0000
vti_filesize:IR|27091
vti_cachedtitle:SR|Recharge prepaid Mobile, DTH and Data Card, Mobile Recharge API
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|H|http://www.Pay2Userecharge.in H|images/favicon.ico Q|css2015/bootstrap.css Q|css2015/font-awesome.min.css Q|css2015/font-awesome.css Q|css2015/my.css A|qr_login_check.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php H|qrregistration.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php H|mailto:care@Pay2Userecharge.in H|qrPay2Userecharge.php H|qrrefer.php K|qrdistributor-ship.php H|index.php S|images2015/logo.png H|index.php H|qrservices.php H|qrdeals-offers.php H|qrbusinessopp.php H|mobilerechargeapi.php H|qrdistributor-ship.php H|qrretailer-ship.php H|qrbulk-sms.php H|qrbusinessopp.php H|data/Pay2Userecharge.apk S|images2015/download_app.png H|qrregistration.php A|qrbusinessaction.php S|captcha_code_file.php H|http://www.s2d6.com/x/ S|http://www.s2d6.com/x/ H|http://www.s2d6.com/x/ S|http://www.s2d6.com/x/ K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php H|http://www.dmca.com/Protection/Status.aspx S|file:///C:/Users/VENKATESH/Documents/My\\ Web\\ Sites/mysite8//images.dmca.com/Badges/DMCA_logo-grn-btn150w.png S|https://streamtest.github.io/badges/streamtest.js K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php H|qrservices.php H|qrterms.php H|qrpolicy.php H|qrpolicy.php H|qrsupportcenter.php H|qrdisclaimer.php H|qrfaq.php H|qrPay2Userecharge.php H|qrbusinessopp.php H|dis-index.php H|ag-index.php H|http://facebook.com/Pay2Userecharge H|http://twitter.com/Pay2UseRecharge H|http://www.linkedin.com/in/Pay2Userecharge H|http://plus.google.com/u/0/108611473967777285008/posts H|http://Pay2Userecharge.wordpress.com/ H|http://m.Pay2Userecharge.in/ H|data/Pay2Userecharge.apk S|images2015/download_app.png K|qrdistributor-ship.php K|qrdistributor-ship.php K|qrdistributor-ship.php H|http://birthdayreminder.in H|http://indiaadmart.com H|http://hakeemindia.com H|http://canaukri.com H|http://anythingstore.in/ H|http://htsm.in S|js2015/jquery-1.10.2.min.js S|js2015/bootstrap.min.js S|js2015/crawler.js
vti_cachedsvcrellinks:VX|NHHS|http://www.Pay2Userecharge.in FHUS|images/favicon.ico FQUS|css2015/bootstrap.css FQUS|css2015/font-awesome.min.css FQUS|css2015/font-awesome.css FQUS|css2015/my.css NAUS|qr_login_check.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FHUS|qrregistration.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php NHUS|mailto:care@Pay2Userecharge.in NHUS|qrPay2Userecharge.php FHUS|qrrefer.php FKUS|qrdistributor-ship.php FHUS|index.php FSUS|images2015/logo.png FHUS|index.php FHUS|qrservices.php NHUS|qrdeals-offers.php NHUS|qrbusinessopp.php FHUS|mobilerechargeapi.php FHUS|qrdistributor-ship.php FHUS|qrretailer-ship.php NHUS|qrbulk-sms.php NHUS|qrbusinessopp.php NHUS|data/Pay2Userecharge.apk FSUS|images2015/download_app.png FHUS|qrregistration.php NAUS|qrbusinessaction.php FSUS|captcha_code_file.php NHHS|http://www.s2d6.com/x/ NSHS|http://www.s2d6.com/x/ NHHS|http://www.s2d6.com/x/ NSHS|http://www.s2d6.com/x/ FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php NHHS|http://www.dmca.com/Protection/Status.aspx NSUS|file:///C:/Users/VENKATESH/Documents/My\\ Web\\ Sites/mysite8//images.dmca.com/Badges/DMCA_logo-grn-btn150w.png NSSS|https://streamtest.github.io/badges/streamtest.js FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FHUS|qrservices.php FHUS|qrterms.php FHUS|qrpolicy.php FHUS|qrpolicy.php FHUS|qrsupportcenter.php FHUS|qrdisclaimer.php FHUS|qrfaq.php NHUS|qrPay2Userecharge.php NHUS|qrbusinessopp.php FHUS|dis-index.php FHUS|ag-index.php NHHS|http://facebook.com/Pay2Userecharge NHHS|http://twitter.com/Pay2UseRecharge NHHS|http://www.linkedin.com/in/Pay2Userecharge NHHS|http://plus.google.com/u/0/108611473967777285008/posts NHHS|http://Pay2Userecharge.wordpress.com/ NHHS|http://m.Pay2Userecharge.in/ NHUS|data/Pay2Userecharge.apk FSUS|images2015/download_app.png FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php FKUS|qrdistributor-ship.php NHHS|http://birthdayreminder.in NHHS|http://indiaadmart.com NHHS|http://hakeemindia.com NHHS|http://canaukri.com NHHS|http://anythingstore.in/ NHHS|http://htsm.in FSUS|js2015/jquery-1.10.2.min.js FSUS|js2015/bootstrap.min.js FSUS|js2015/crawler.js
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=UTF-8 viewport width=device-width,\\ initial-scale=1 keywords Pay2UseRecharge.in,\\ Recharge\\ prepaid\\ Mobile,\\ DTH\\ and\\ Data\\ Card\\ Online\\ by\\ using\\ your\\ Credit/Debit\\ Card,\\ Netbanking,\\ instant\\ recharge\\ for\\ Airtel,\\ Aircel,\\ Vodafone,\\ LOOP,\\ BPL,\\ Reliance,\\ Idea,\\ BSNL,\\ Virgin\\ and\\ Tata\\ Indicom\\ for\\ all\\ circles\\ across\\ India,\\ TataSky,\\ Airtel\\ Digital\\ TV,\\ Videocon\\ D2H,\\ BigTV,\\ Sun\\ Direct\\ DTH,\\ Tata\\ Photon,\\ MBlaze,\\ Reliance\\ NetConnetct\\ Data\\ Card,\\ Mobile\\ Recharge\\ API\\ provider description Recharge\\ prepaid\\ Mobile,\\ DTH\\ and\\ Data\\ Card\\ Online\\ by\\ using\\ your\\ Credit/Debit\\ Card,\\ Net\\ Banking,\\ and\\ instant\\ recharge\\ for\\ all\\ operators\\ of\\ India,\\ Mobile\\ Recharge\\ API\\ provider Search_Engines Google,\\ MSN,\\ Bing,\\ Overture,\\ AltaVista,\\ Yahoo,\\ AOL,\\ Infoseek,\\ LookSmart,\\ Excite,\\ Hotbot,\\ Lycos,\\ Magellan,\\ CNET,\\ DogPile,\\ Ask\\ Jeeves,\\ Teoma,\\ Snap,\\ Webcrawler robot index,follow robots noodp,noydir revisit-after 7\\ days googlebot noodp slurp noodp bingbot noodp rating General refresh 10 copyright Copyright\\ \\ 2014\\ htsm.in.\\ All\\ Rights\\ Reserved. author K.\\ Prakash generator htsm.in language en content-language en geo.region IN-WB geo.placename Kolkata
vti_charset:SR|utf-8
vti_generator:SR|htsm.in
